name: "ensemble_model"
max_batch_size: 0 
platform: "ensemble"

input [
{
    name: "prompt"
    data_type: TYPE_STRING
    dims: [ -1 ] 
}
]

output [
{
    name: "output_0"
    data_type: TYPE_FP32
    dims: [-1, 2] 
}
]

ensemble_scheduling {
    step [
        {
            model_name: "tokenizer"
            model_version: -1
            input_map {
            key: "prompt"
            value: "prompt"
        }
        output_map [
        {
            key: "input_ids"
            value: "input_ids"
        },
        {
            key: "attention_mask"
            value: "attention_mask"
        }
        ]
        },
        {
            model_name: "model"
            model_version: -1
        input_map [
            {
                key: "input_ids"
                value: "input_ids"
            },
            {
                key: "attention_mask"
                value: "attention_mask"
            }
        ]
        output_map {
                key: "output_0"
                value: "output_0"
            }
        }
    ]
}
